### ISSUE TITLE
Where is the Zipper part?

### ISSUE THREAD

**Issue by That-David-Guy** [ccapndave/elm-typed-tree#1]
Hi

This library looks exactly like what I'm looking for, a fixed height tree with different types at each branch + a zipper. But looking through the docs I can't actually find the zipper part? 

I'm assuming the zipper to look something like: 

- Before list
- selected
- After list

for each level of the tree.

It's been a while since uni and I'm probably misremembering something here.

For context, I'm trying to build a rich text editor and the tree would look something like this:

- Buffer
-- Lines
--- LineItems (e.g. plain text, mentions)

The zipper would be where the cursor is

**Comment by ccapndave** [comment]
This library doesn't actually use the traditional zipper construct, instead it has `TreePath`s which store the entire tree, plus a recursive structure of indexes which are the branch that was chosen at each point.  I'm afraid this means that it's mainly useful for navigating around trees, but not for editing them.

**Comment by That-David-Guy** [comment]
Thanks for the quick clarification 👍. I'll close the issue.
